In [1]:
import numpy  as np

 # BASICS OF NUMPY

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
### This is a two dimesional array in numpy
b =np.array([[3,4.2,9],[6.0,5.0,4.0]])
print(b)

[[3.  4.2 9. ]
 [6.  5.  4. ]]


In [7]:
# Get dimension of the array
a.ndim

1

In [9]:
# Get shape of "a".. which is a one dimesional array 
a.shape

(3,)

In [10]:
# Get shape of "b".. which is a two dimesional array 
b.shape

(2, 3)

In [13]:
## getting data type of the array "b"
b.dtype

dtype('float64')

In [15]:
## getting data type of the array  and it's size it occupies like below it's an int of size 32"a"
a.dtype

dtype('int32')

### (.itemsize) Returns the size (in bytes) of each element in the array.

In [19]:
# get size of an array ..like how many bytes does this array ocuupy in memeory 
a.itemsize

4

In [20]:
# for "b" the bytes are 
b.itemsize

8

### (.size)  Returns the total number of elements in the array

In [21]:
 a.size

3

In [22]:
b.size

6

### (.nbytes)  Returns the total number of bytes consumed by the array

In [23]:
a.nbytes

12

## Accessing/Changing specific elements ,rows, columns ,etc

In [24]:
# Create a 2x7 array of integers
a = np.array([[1, 2, 3, 4, 5, 6, 7],
                  [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
# get specific  element  [r,c].... we use that way of [row(r), column(c)]
a[1,5]

13

In [26]:
# get a specific row .....":"... that means all ...like first row and all it's data in it 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])